### ISSUE TITLE
Saving theme causes redirect to error page

### ISSUE THREAD

**Issue by wrmilling** [toboshii/hajimari#12]
**Describe the Bug**
When selecting a new theme and hitting save, I am redirected to a empty page with the text `startpage not found`. 

**To Reproduce**
1. Go to `https://hajimari.k.example.org/`
2. Click on hamburger menu in bottom left.
3. Select new theme from the listed options
4. Click on `Save` in the Options modal

**Expected Behavior**
Theme is saved and the modal closes or indicates the saved state

**Actual Behavior**
I am redirected to a new URL (example: `https://hajimari.k.example.org/J3KP51T9zfYPOExLjiJuq`) with the `startpage not found` text. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux, POP_OS! 21.04
 - Browser: Firefox 
 - Version: 91.0.1

**Comment by toboshii** [comment]
This was resolved on Discord.
Issue was persistence not being writable by the Hajimari user. It was fixed by applying a `podSecurityContext`.

**Comment by allenporter** [comment]
This also seems to happen if you don't have persistence configured at all. (the default)

**Comment by lenaxia** [comment]
Since I wasn't able to find any reference to a discord server on the hajimari.io page or github, and it wasn't quite clear to me what it meant to just apply a podSecurityContext, leaving the solution here for people that may run into this issue. 

In your values.yaml (or helmrelease), add the following:

```values:
  podSecurityContext:
    fsGroup: 101```

The Hajimari user in the pod is in group 101, so doing this makes sure to mount all volumes/persistence with the hajimari group (101) so that the pod can write to the persistence.
